DESC USER1;
DESC PRODUCT;
DESC PROD_ORDER;
DESC PAY;
SELECT * FROM USER1;

DROP TABLE PAY;
DROP TABLE REVIEW;
DROP TABLE PROD_ORDER;
CREATE TABLE "PROD_ORDER" (
    "ORDER_NO" NUMBER PRIMARY KEY,
    "USER_ID" VARCHAR2(30)  NOT NULL,
    "P_CODE" VARCHAR2(6) NOT NULL,
    "ORDER_COUNT" NUMBER NOT NULL,
    "ORDER_PRICE" NUMBER NOT NULL,
    "ORDER_DATE" VARCHAR2(300) DEFAULT TO_CHAR(SYSDATE, 'yyyy/MM/dd hh24:mi:ss') NOT NULL,
    "USER_PHONE" VARCHAR2(20) NOT NULL,
    "ORDER_ADDR" VARCHAR2(100) NOT NULL,
    "DELIVER_COMPANY" VARCHAR2(50) DEFAULT '우체국 택배' NOT NULL,
    "DELIVER_NUM" NUMBER NOT NULL UNIQUE,
    "DELIVER_STATE" VARCHAR2(30) DEFAULT '배송 전' NOT NULL,
    CONSTRAINT PROD_ORDER_FK1 FOREIGN KEY(USER_ID) REFERENCES USER1(USER_ID),
    CONSTRAINT PROD_ORDER_FK2 FOREIGN KEY(P_CODE) REFERENCES PRODUCT(P_CODE)
);
CREATE TABLE "PAY" (
	"PAY_NO"	NUMBER		PRIMARY KEY,
	"ORDER_NO"	NUMBER		NOT NULL,
    "PAY_TYPE"  VARCHAR2(50)    NOT NULL,
    "PAY_PRICE" NUMBER NOT NULL,
    "PAY_DATE" VARCHAR2(300) DEFAULT TO_CHAR(SYSDATE, 'yyyy/MM/dd hh24:mi:ss') NOT NULL,
    CONSTRAINT PAY_FK FOREIGN KEY(ORDER_NO) REFERENCES PROD_ORDER(ORDER_NO)
);
CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER		PRIMARY KEY,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"REVIEW_DATE"	VARCHAR2(300)   DEFAULT TO_CHAR(SYSDATE, 'yyyy/MM/dd hh24:mi:ss') NOT NULL,
    "REVIEW_TITLE"  VARCHAR2(100)   NOT NULL,
	"REVIEW_TEXT"	VARCHAR2(1000)		NOT NULL,
	"REVIEW_STAR"	NUMBER		DEFAULT '5',
    CONSTRAINT REVIEW_FK1 FOREIGN KEY(USER_ID) REFERENCES USER1(USER_ID),
    CONSTRAINT REVIEW_FK2 FOREIGN KEY(ORDER_NO) REFERENCES PROD_ORDER(ORDER_NO)
);

select * from notice;
select * from prod_order;
desc prod_order;
desc pay;
select * from pay;
select a.pay_no, a.pay_type, a.pay_price, a.pay_date,
b.* from pay a, prod_order b where a.order_no = b.order_no;
desc user1;
select * from user1;
desc basket;
desc product;
SELECT * FROM PRODUCT;


--ALTER TABLE PROD_ORDER RENAME COLUMN ORDER_COMPANY TO DELIVER_COMPANY;
--ALTER TABLE PROD_ORDER RENAME COLUMN ORDER_NUM TO DELIVER_NUM;
--ALTER TABLE PROD_ORDER RENAME COLUMN ORDER_STATE TO DELIVER_STATE;
--INSERT INTO PROD_ORDER VALUES(1, 'user1', '347', 1, 199999, default, '01043214321', '경기도 고양시 일산동구
--', default, '000000000001', default);
--INSERT INTO PROD_ORDER VALUES(2, 'user2', '358', 1, 99000, default, '01011111111', '경기도 파주시 문산읍
--', default, '000000000002', default);
--INSERT INTO PROD_ORDER VALUES(3, 'user3', '356', 3, 74700, default, '01033333333', '경기도 김포시 통진읍
--', default, '000000000003', default);
--delete from prod_order where order_no=1;
--delete from prod_order where order_no=2;
--delete from prod_order where order_no=3;
select p_code from (select * from product where catno like '01%' order by p_code desc) where rownum=1;
SELECT ORDER_NO FROM (SELECT ORDER_NO FROM PROD_ORDER ORDER BY ORDER_NO DESC) WHERE ROWNUM=1;
SELECT P_CODE FROM PRODUCT WHERE CATNO LIKE '01%' ORDER BY P_CODE DESC;
COMMIT;